site_name: PL&T - Physics Learning and Teaching
site_url: https://pi-master/PLT
repo_url: https://github.com/Andy-UTAS/PhysicsL-T
repo_name:  Andy-UTAS/PhysicsL&T
edit_uri: ""

nav:
    - Home: index.md
    - 'Teaching':
      - teaching/index.md
      - teaching/practicalities.md
      - teaching/lms.md
      - teaching/website.md
      - teaching/mkdocs.md
      - teaching/computation.md
      - teaching/demonstrations.md
    - 'Assessment':
      - assessment/index.md
      - assessment/guidelines.md
      - assessment/assignments.md
      - assessment/examination.md
    - 'Administration':
      - administration/index.md
      - administration/bureaucracy.md
      - administration/enrolments.md
    - 'Resources':
      - resources/index.md
      - resources/faqs.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: orange
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: orange
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: logo.png
  favicon: logo.png
  features:
  #  - navigation.expand
    - navigation.top # Include a "back to top" button
    - navigation.tabs # Use tabs rather than sections
    - navigation.sections # Render sections as groups
    - navigation.indexes # Include section index pages
    - toc.integrate # Integrate the table of contents into the left index
    - search.highlight
    - content.code.annotate
  highlightjs: True
  icon:
    repo: fontawesome/brands/git-alt
  # custom_dir: overrides # Initially here for banner usage, but this was not very good

plugins:
  - mkdocs-video # allows for video
  - search # enables search
  # - encryptcontent:
      # global_password: 'thisisapassword'
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True
  - toc:
      permalink: True
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      linenums: true # Enabeles line numbers in code
      linenums_style: pymdownx-inline # Makes the line numbers in code not shit (renders properly and copies well)
      anchor_linenums: True
  - pymdownx.inlinehilite
  - pymdownx.tabbed # Enabeles content tabs
  - pymdownx.superfences # Enables nesting of code and content in tabs
  - pymdownx.snippets # Allows for a global list of acronyms
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.extra
  - abbr
  - footnotes
  - meta

extra_css:
  - 'https://use.fontawesome.com/releases/v5.8.1/css/all.css'
#  - scripts/custom.css
  - stylesheets/extra.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/MathJax.js?config=TeX-AMS_HTML'
  - 'https://unpkg.com/thebelab@0.5.0/lib/index.js'
  - 'scripts/mathjaxhelper.js'
  - 'scripts/thebelabhelper.js'
  - 'scripts/x3dom.js'

copyright: Content prepared and curated by <a href="mailto:andrew.mcculloch@utas.edu.au">A J McCulloch</a>
